name: "Genome Maintenance and Evolution lab | @GIMM"
description: "FumaLab - Genome Maintenance and Evolution - Marco Fumasoni"

url: "https://fumalab.github.io"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"
google_analytics: G-37E9W9RT20
permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true
